# Generated by Django 5.0.3 on 2024-08-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table='Choice',
        ),
        migrations.AlterModelTable(
            name='question',
            table='Question',
        ),
    ]
